name: Cargo Build & Test

on:
  push:
    branches: [ "main", "rs/*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install OS Dependencies
      run: |
        sudo apt-get install libxcb-xfixes0-dev
        sudo apt-get install libxcb-shape0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
